package aman.catalog.audio.models

object SortOption {

    enum class Track {
        TITLE_ASC, TITLE_DESC, 
        ARTIST_ASC, ARTIST_DESC,
        ALBUM_ARTIST_ASC, ALBUM_ARTIST_DESC,
        ALBUM_ASC, ALBUM_DESC,
        DATE_ADDED_DESC, DATE_ADDED_ASC,  
        YEAR_DESC, YEAR_ASC,
        DURATION_DESC, DURATION_ASC,
        PLAY_COUNT_DESC, PLAY_COUNT_ASC,
        RECENTLY_PLAYED,
        DATE_MODIFIED_DESC, DATE_MODIFIED_ASC
    }

    enum class Album {
        TITLE_ASC, TITLE_DESC, 
        ARTIST_ASC, ARTIST_DESC,
        DATE_ADDED_DESC, DATE_ADDED_ASC,
        YEAR_DESC, YEAR_ASC,
        DURATION_DESC, DURATION_ASC,
        TRACK_COUNT_DESC, TRACK_COUNT_ASC,
        PLAY_COUNT_DESC, PLAY_COUNT_ASC, 
        RECENTLY_PLAYED
    }

    enum class Artist {
        NAME_ASC, NAME_DESC, TRACK_COUNT_DESC, TRACK_COUNT_ASC, ALBUM_COUNT_DESC, ALBUM_COUNT_ASC, DURATION_DESC, DURATION_ASC, PLAY_COUNT_DESC, PLAY_COUNT_ASC, RECENTLY_PLAYED
    }

    enum class Genre {
        NAME_ASC, NAME_DESC, TRACK_COUNT_DESC, TRACK_COUNT_ASC, ALBUM_COUNT_DESC, ALBUM_COUNT_ASC, DURATION_DESC, DURATION_ASC, PLAY_COUNT_DESC, PLAY_COUNT_ASC, RECENTLY_PLAYED
    }

    enum class Composer {
        NAME_ASC, NAME_DESC, TRACK_COUNT_DESC, TRACK_COUNT_ASC, ALBUM_COUNT_DESC, ALBUM_COUNT_ASC, DURATION_DESC, DURATION_ASC, PLAY_COUNT_DESC, PLAY_COUNT_ASC, RECENTLY_PLAYED
    }

    enum class Lyricist {
        NAME_ASC, NAME_DESC, TRACK_COUNT_DESC, TRACK_COUNT_ASC, ALBUM_COUNT_DESC, ALBUM_COUNT_ASC, DURATION_DESC, DURATION_ASC, PLAY_COUNT_DESC, PLAY_COUNT_ASC, RECENTLY_PLAYED
    }

    enum class Folder {
        NAME_ASC, NAME_DESC, PATH_ASC, PATH_DESC, TRACK_COUNT_DESC, TRACK_COUNT_ASC, ALBUM_COUNT_DESC, ALBUM_COUNT_ASC, DURATION_DESC, DURATION_ASC, PLAY_COUNT_DESC, PLAY_COUNT_ASC, RECENTLY_PLAYED
    }

    enum class Year {
        YEAR_DESC, YEAR_ASC, TRACK_COUNT_DESC, TRACK_COUNT_ASC, ALBUM_COUNT_DESC, ALBUM_COUNT_ASC, DURATION_DESC, DURATION_ASC, PLAY_COUNT_DESC, PLAY_COUNT_ASC, RECENTLY_PLAYED
    }

    enum class Playlist {
        NAME_ASC, NAME_DESC, TRACK_COUNT_DESC, TRACK_COUNT_ASC, DURATION_DESC, DURATION_ASC, DATE_CREATED_DESC, DATE_CREATED_ASC, DATE_MODIFIED_DESC, DATE_MODIFIED_ASC
    }
}
